// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe36l1hjFeGrBgXIvpd4PkRl_00yN-fXw',
    appId: '1:319928501602:web:227bd42523e0651eef583b',
    messagingSenderId: '319928501602',
    projectId: 'uf-parking-map',
    authDomain: 'uf-parking-map.firebaseapp.com',
    databaseURL: 'https://uf-parking-map-default-rtdb.firebaseio.com',
    storageBucket: 'uf-parking-map.appspot.com',
    measurementId: 'G-C77237DNVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwxtfjo-QtYcGj_zGzDBiBXq1ic9lROXw',
    appId: '1:319928501602:android:bb72ba0e406fd154ef583b',
    messagingSenderId: '319928501602',
    projectId: 'uf-parking-map',
    databaseURL: 'https://uf-parking-map-default-rtdb.firebaseio.com',
    storageBucket: 'uf-parking-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBShwEd7nRCuxFSB6eMmNeZZf3Xzjsk-To',
    appId: '1:319928501602:ios:18530933b5c898ecef583b',
    messagingSenderId: '319928501602',
    projectId: 'uf-parking-map',
    databaseURL: 'https://uf-parking-map-default-rtdb.firebaseio.com',
    storageBucket: 'uf-parking-map.appspot.com',
    androidClientId: '319928501602-4r3l9v15nl3g5r1mvq77e9mjq03d5lag.apps.googleusercontent.com',
    iosClientId: '319928501602-a0vgv7j8oomivvj62og55oa875m4a3mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBShwEd7nRCuxFSB6eMmNeZZf3Xzjsk-To',
    appId: '1:319928501602:ios:18530933b5c898ecef583b',
    messagingSenderId: '319928501602',
    projectId: 'uf-parking-map',
    databaseURL: 'https://uf-parking-map-default-rtdb.firebaseio.com',
    storageBucket: 'uf-parking-map.appspot.com',
    androidClientId: '319928501602-4r3l9v15nl3g5r1mvq77e9mjq03d5lag.apps.googleusercontent.com',
    iosClientId: '319928501602-a0vgv7j8oomivvj62og55oa875m4a3mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkings',
  );
}
